### ISSUE TITLE
Any plan about the docker version?

### ISSUE THREAD

**Issue by valuex** [ankicommunity/djankiserv#18]
Hi,
I've read related issues and learned that djankiserv is going to replace anki-sync-server.
How about the plan for the docker version? 
I think there are plenty of  users are waiting for the docker version of djankiserv  so that he or she can upgrade to the most-recently updated version of ANKI.
Thanks.

**Comment by AntonOfTheWoods** [comment]
Hi @valuex , sorry about not getting back sooner. There are (and have always been actually) container versions of `djankiserv`. https://hub.docker.com/repository/docker/ankicommunity/djankiserv
The other project maintainers seem to use docker/docker-compose - I do not. I have even stopped using it to build images, and instead use `buildah` (which has its issues but doesn't need a stupid daemon to create an image).
The question is really, what are you expecting in terms of "docker support"? If it is just an image, then that is easy, and I will try and make sure there are up-to-date images going forward.. If you want all of the extra docker-specific stuff like a compose file, @kuklinistvan is mainly supporting that side in the community, so I'll let him respond to that.

**Comment by VikashKothary** [comment]
Yep. Like @AntonOfTheWoods said, there's already a Docker image for Djankiserv and I'm just working on updating our devops repo to include the entire toolchain from Docker images to Helm Charts for both servers. 

I would suggest following the repo for Docker related stuff.

**Comment by valuex** [comment]
@AntonOfTheWoods  Thanks for your reply.   I have been using anki-sync-server (docker) to sync my decks between Anki desktop and Ankidroid.  But recently Anki updates and anki-sync-server is not compatible to the latest Anki anymore. So I am looking for a new solution and found **djankiserv**.    Right now, there is very limited infomation on installing. It would be great for providing some instruction on how to do docker related settings, such as ports and volume. Thanks again for your work on djankiserv again.

**Comment by VikashKothary** [comment]
@valuex Like I mentioned, the docker related issues should be discussed in our devops repo. I would recommend following this ticket: https://github.com/ankicommunity/anki-devops-services/issues/11. 

Can we close this ticket and continue the conversation there. Many thanks.

**Comment by valuex** [comment]
@VikashKothary Get it, thanks for your helpful information.
