### ISSUE TITLE
Move Anki Addon to Community Repo

### ISSUE THREAD

**Issue by VikashKothary** [ankicommunity/djankiserv#4]
The repo is here: https://github.com/ankicommunity/anki-desktop-addons.

This is more a initiative because we've got a lot of addons flying around. We moving them all to one place.

**Comment by AntonOfTheWoods** [comment]
@VikashKothary , is this fixed by https://github.com/ankicommunity/djankiserv/pull/10 ?

**Comment by VikashKothary** [comment]
Yep. Thanks so much. + @kuklinistvan great job.
