### ISSUE TITLE
500 Internal Server Error at `/applyChanges` with AnkiDroid

### ISSUE THREAD

**Issue by kuklinistvan** [ankicommunity/djankiserv#7]
Hello,

I'm currently crafting the user friendly (as much as possible) Docker image and Docker Compose configuration. See the progress here:

*  https://github.com/ankicommunity/docker-anki-sync-server/tree/djankiserv-incorp
*  https://github.com/ankicommunity/docker-anki-sync-server/tree/djankiserv-incorp/Docker%20Compose/djankiserv-postgres-nginx

I have successfully launched a server with this stack:
* djankiserv at https://github.com/kuklinistvan/djankiserv/commit/bec42f33d6afceeec3173389d5cf6337ff4cc071

  This is a fork which only contains some pending documentation in a PR, and one additional reverted commit https://github.com/ankicommunity/djankiserv/commit/bdbffe922bfe2e6fcd45198f578ff9de1b37ca9c, which breaks the requirements in the Docker image. It was added a couple hours ago :) I know it is not the right solution and I will fix it later, just wanted to get straight to the point.

* PostgreSQL 13.1
* NGINX 1.19.5, proxy and static file server, plain http

On the client side: 

* AnkiDesktop 2.1.35
* AnkiDroid 2.14.1

On Anki Desktop the synchronization seems to work more or less. On AnkiDroid I get a generic error message. See also:

* [The exception in `adb logcat`](https://pastebin.com/D0Z3LVQs)
* [The error in the compose log](https://pastebin.com/4kXEsxi3)

**Comment by AntonOfTheWoods** [comment]
Sorry for the delay @kuklinistvan  . Can you repro in a dev setup, alternatively, can you share the db that causes this?

**Comment by AntonOfTheWoods** [comment]
@kuklinistvan ping.

**Comment by kuklinistvan** [comment]
Hello, sorry the delay.

It happened at the time of my attempt to build a `docker-compose` setup. I'll reopen this issue with detailed instructions for reproduction later.

Thanks!
